name: Check homework
on: [push]
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8.8]
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: python -m unittest ./../tests/sumtest.py 
    steps:
      - name: Run dir
        run: ls
